version: "3"
services:
  maven:
    build: ./maven
  tomcat:
    image: tomcat:9
    volumes:
      - type: bind
        source: ./boxboxfuse-sample-java-war-hello/target
        target: /usr/local/tomcat/webapps
    ports:
      - "8080:8080"
    depends_on:
      - maven