version: "3"
services:
  maven:
    build: maven
  tomcat:
    image: tomcat:9
    volumes:
      - type: volume
        source: /usr/src/mymaven/target
        target: /usr/local/tomcat/webapps
    ports:
      - "8080:8080"