version: '3'
services:
  maven:
    build: ./maven
    volumes: 
      - ./boxfuse:/usr/src/mymaven
      - prod:/usr/src/prod
    command: > 
        bash -c "mvn clean install
        && cp /usr/src/mymaven/target/*.war /usr/src/prod"
  tomcat:
    build: ./tomcat
    volumes:
      - prod:/usr/local/tomcat/webapp
    ports:
      - "8080:8080"
volumes:
  prod: