version: '3'
services:
  maven:
    build: ./maven
    volumes: 
      - ./boxfuse:/usr/src/mymaven
    command: mvn clean install
  tomcat:
    build: ./tomcat
    volumes:
      - ./boxfuse/target:/usr/local/tomcat/webapp
    ports:
      - "8080:8080"